/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.awt.image.DataBufferByte;
import java.lang.reflect.Field;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import org.opencv.core.Core;
import org.opencv.core.CvType;
import org.opencv.core.Mat;
import org.opencv.core.MatOfPoint;
import org.opencv.core.Point;
import org.opencv.core.Rect;
import org.opencv.core.Scalar;
import org.opencv.core.Size;
import org.opencv.imgcodecs.Imgcodecs;
import org.opencv.imgproc.Imgproc;

/**
 *
 * @author Yogha Pradana
 */
public class MainWindow extends javax.swing.JFrame {

    JFileChooser fc;
    Mat img_awal, img_hsv, h, s, v, mask, blur, canny, hirarki;
    ArrayList<Mat> hsv, hsv_thres, data;
    List<MatOfPoint> kontur;
    boolean opened = false;
    double scale;
    WindowTuning w;
    Extend x;

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        w = new WindowTuning();
        w.setVisible(false);
        x = new Extend();
        x.setVisible(false);

        img_awal = new Mat();
        h = new Mat();
        s = new Mat();
        v = new Mat();
        mask = new Mat();
        blur = new Mat();
        canny = new Mat();
        hirarki = new Mat();
        hsv_thres = new ArrayList<Mat>();
        hsv = new ArrayList<Mat>();
        kontur = new ArrayList<>();
        fc = new JFileChooser(System.getProperty("user.dir"));
        //x =new Extend();
        // x.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btn_open = new javax.swing.JButton();
        lbl_img_src = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lbl_img_s = new javax.swing.JLabel();
        slider_h = new javax.swing.JSlider();
        slider_h1 = new javax.swing.JSlider();
        lbl_h1_val = new javax.swing.JLabel();
        lbl_h_val = new javax.swing.JLabel();
        slider_s1 = new javax.swing.JSlider();
        lbl_s_val = new javax.swing.JLabel();
        lbl_s1_val = new javax.swing.JLabel();
        slider_s = new javax.swing.JSlider();
        slider_v = new javax.swing.JSlider();
        slider_v1 = new javax.swing.JSlider();
        lbl_v1_val = new javax.swing.JLabel();
        lbl_v_val = new javax.swing.JLabel();
        lbl_img_v = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbl_img_h = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lbl_img_h_thres = new javax.swing.JLabel();
        lbl_img_s_thres = new javax.swing.JLabel();
        lbl_img_v_thres = new javax.swing.JLabel();
        lbl_img_mask = new javax.swing.JLabel();
        fieldArea = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        fieldOverlap = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btn_thres = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        labelResult = new javax.swing.JLabel();
        lbl_img_other = new javax.swing.JLabel();
        btnSVM = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("program");
        setBackground(new java.awt.Color(225, 225, 225));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(424, 705));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_open.setText("Open Image");
        btn_open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_openActionPerformed(evt);
            }
        });
        jPanel2.add(btn_open, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        lbl_img_src.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_img_src.setToolTipText("");
        lbl_img_src.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lbl_img_src.setBorder(javax.swing.BorderFactory.createTitledBorder("Source"));
        jPanel2.add(lbl_img_src, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 210, 160));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel1.setText("Preprocessing and Segmentation of Input Image");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 14, -1, -1));

        jPanel3.setBackground(new java.awt.Color(196, 196, 196));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_img_s.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lbl_img_s.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_img_s.setToolTipText("");
        lbl_img_s.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lbl_img_s.setBorder(javax.swing.BorderFactory.createTitledBorder("Channel S"));
        jPanel3.add(lbl_img_s, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 156, 102));

        slider_h.setBackground(new java.awt.Color(196, 196, 196));
        slider_h.setMaximum(180);
        slider_h.setValue(0);
        slider_h.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        slider_h.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                slider_hMouseDragged(evt);
            }
        });
        slider_h.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                slider_hMouseReleased(evt);
            }
        });
        jPanel3.add(slider_h, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 151, 130, -1));

        slider_h1.setBackground(new java.awt.Color(196, 196, 196));
        slider_h1.setMaximum(180);
        slider_h1.setValue(180);
        slider_h1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        slider_h1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                slider_h1MouseDragged(evt);
            }
        });
        slider_h1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                slider_h1MouseReleased(evt);
            }
        });
        jPanel3.add(slider_h1, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 178, 130, -1));

        lbl_h1_val.setText("0");
        jPanel3.add(lbl_h1_val, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 178, 34, -1));

        lbl_h_val.setText("0");
        jPanel3.add(lbl_h_val, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 151, 34, -1));

        slider_s1.setBackground(new java.awt.Color(196, 196, 196));
        slider_s1.setMaximum(255);
        slider_s1.setValue(255);
        slider_s1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        slider_s1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                slider_s1MouseDragged(evt);
            }
        });
        slider_s1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                slider_s1MouseReleased(evt);
            }
        });
        jPanel3.add(slider_s1, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 178, 130, -1));

        lbl_s_val.setText("0");
        jPanel3.add(lbl_s_val, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 151, 25, -1));

        lbl_s1_val.setText("0");
        jPanel3.add(lbl_s1_val, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 178, 25, -1));

        slider_s.setBackground(new java.awt.Color(196, 196, 196));
        slider_s.setMaximum(255);
        slider_s.setValue(0);
        slider_s.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        slider_s.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                slider_sMouseDragged(evt);
            }
        });
        slider_s.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                slider_sMouseReleased(evt);
            }
        });
        jPanel3.add(slider_s, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 151, 130, -1));

        slider_v.setBackground(new java.awt.Color(196, 196, 196));
        slider_v.setMaximum(255);
        slider_v.setValue(0);
        slider_v.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        slider_v.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                slider_vMouseDragged(evt);
            }
        });
        slider_v.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                slider_vMouseReleased(evt);
            }
        });
        jPanel3.add(slider_v, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 110, -1));

        slider_v1.setBackground(new java.awt.Color(196, 196, 196));
        slider_v1.setMaximum(255);
        slider_v1.setValue(255);
        slider_v1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        slider_v1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                slider_v1MouseDragged(evt);
            }
        });
        slider_v1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                slider_v1MouseReleased(evt);
            }
        });
        jPanel3.add(slider_v1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, 110, -1));

        lbl_v1_val.setText("0");
        jPanel3.add(lbl_v1_val, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 180, 28, -1));

        lbl_v_val.setText("0");
        jPanel3.add(lbl_v_val, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 150, 28, -1));

        lbl_img_v.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lbl_img_v.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_img_v.setToolTipText("");
        lbl_img_v.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lbl_img_v.setBorder(javax.swing.BorderFactory.createTitledBorder("Channel V"));
        jPanel3.add(lbl_img_v, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 38, 156, 102));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel2.setText("Tunning HSV");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 4, -1, -1));

        lbl_img_h.setBackground(new java.awt.Color(255, 255, 255));
        lbl_img_h.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lbl_img_h.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_img_h.setToolTipText("");
        lbl_img_h.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lbl_img_h.setBorder(javax.swing.BorderFactory.createTitledBorder("Channel H"));
        jPanel3.add(lbl_img_h, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 38, 156, 102));

        jLabel10.setText("HI");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jLabel11.setText("LOW");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel12.setText("LOW");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, -1, -1));

        jLabel14.setText("HI");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, -1, -1));

        jLabel15.setText("LOW");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, -1, -1));

        jLabel16.setText("HI");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 44, 595, -1));

        jPanel5.setBackground(new java.awt.Color(196, 196, 196));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel4.setText("Result Threshold");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        lbl_img_h_thres.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lbl_img_h_thres.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_img_h_thres.setToolTipText("");
        lbl_img_h_thres.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lbl_img_h_thres.setBorder(javax.swing.BorderFactory.createTitledBorder("Thres H"));
        jPanel5.add(lbl_img_h_thres, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 38, 156, 102));

        lbl_img_s_thres.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lbl_img_s_thres.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_img_s_thres.setToolTipText("");
        lbl_img_s_thres.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lbl_img_s_thres.setBorder(javax.swing.BorderFactory.createTitledBorder("Thres S"));
        jPanel5.add(lbl_img_s_thres, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 38, 156, 102));

        lbl_img_v_thres.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lbl_img_v_thres.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_img_v_thres.setToolTipText("");
        lbl_img_v_thres.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lbl_img_v_thres.setBorder(javax.swing.BorderFactory.createTitledBorder("Thres V"));
        jPanel5.add(lbl_img_v_thres, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 38, 156, 102));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 600, 170));

        lbl_img_mask.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lbl_img_mask.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_img_mask.setToolTipText("");
        lbl_img_mask.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lbl_img_mask.setBorder(javax.swing.BorderFactory.createTitledBorder("Mask"));
        jPanel1.add(lbl_img_mask, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 177, 97));

        fieldArea.setText("10");
        jPanel1.add(fieldArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 550, 38, -1));

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel5.setText("Result Mask");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, -1));

        fieldOverlap.setText("80");
        fieldOverlap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldOverlapActionPerformed(evt);
            }
        });
        jPanel1.add(fieldOverlap, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 580, 38, -1));

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel6.setText("Limit");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, -1, -1));

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel7.setText("Overlap");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, -1, -1));

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel8.setText(":");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 550, 13, -1));

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel9.setText(":");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 580, 14, -1));

        btn_thres.setText("Run");
        btn_thres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thresActionPerformed(evt);
            }
        });
        jPanel1.add(btn_thres, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 580, 83, -1));

        jPanel6.setBackground(new java.awt.Color(196, 196, 196));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel13.setText("Result");
        jPanel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        labelResult.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        labelResult.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " Result Decision", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 12))); // NOI18N
        jPanel6.add(labelResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 38, 130, 49));

        lbl_img_other.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_img_other.setToolTipText("");
        lbl_img_other.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lbl_img_other.setBorder(javax.swing.BorderFactory.createTitledBorder("Leukemia Detection"));
        lbl_img_other.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_img_otherMouseClicked(evt);
            }
        });
        jPanel6.add(lbl_img_other, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 184, 127));

        btnSVM.setText("Decision");
        btnSVM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSVMActionPerformed(evt);
            }
        });
        jPanel6.add(btnSVM, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 90, -1));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 430, 350, 180));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 680, 630));

        jPanel4.setBackground(new java.awt.Color(196, 196, 196));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 900, 10));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel3.setText("LEUKEMIA DETECTION");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jButton2.setText("Dataset");
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setFocusPainted(false);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 130, 40));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jButton3.setText("About");
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setFocusPainted(false);
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton3MouseExited(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 130, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 925, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_openActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_openActionPerformed
        // TODO add your handling code here:
        if (fc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            img_awal = Imgcodecs.imread(fc.getSelectedFile().getPath(), Imgcodecs.IMREAD_COLOR);

            img_hsv = new Mat();
            Imgproc.cvtColor(img_awal, img_hsv, Imgproc.COLOR_BGR2HSV);

            Core.split(img_hsv, hsv);

            System.out.println("HSV channel : " + hsv.size());

            System.out.println("panel height= " + lbl_img_src.getHeight());
            System.out.println("image height= " + img_awal.size().height);

            Draw.drawToLabelScaled(img_awal, lbl_img_src);

            Draw.drawToLabelScaled(hsv.get(0), lbl_img_h);
            Draw.drawToLabelScaled(hsv.get(1), lbl_img_s);
            Draw.drawToLabelScaled(hsv.get(2), lbl_img_v);

            opened = true;
            h = Process.hsvThres(lbl_h_val, lbl_h1_val, slider_h, slider_h1, img_hsv, lbl_img_h_thres, 0);
            s = Process.hsvThres(lbl_s_val, lbl_s1_val, slider_s, slider_s1, img_hsv, lbl_img_s_thres, 1);
            v = Process.hsvThres(lbl_v_val, lbl_v1_val, slider_v, slider_v1, img_hsv, lbl_img_v_thres, 2);

            //drawtoLabel(img_awal, pnl_open);
        }
    }//GEN-LAST:event_btn_openActionPerformed

    private void slider_hMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slider_hMouseReleased
        // TODO add your handling code here:
        if (opened)
            h = Process.hsvThres(lbl_h_val, lbl_h1_val, slider_h, slider_h1, img_hsv, lbl_img_h_thres, 0);
    }//GEN-LAST:event_slider_hMouseReleased

    private void slider_hMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slider_hMouseDragged
        // TODO add your handling code here:
        if (opened)
            h = Process.hsvThres(lbl_h_val, lbl_h1_val, slider_h, slider_h1, img_hsv, lbl_img_h_thres, 0);
    }//GEN-LAST:event_slider_hMouseDragged

    private void slider_sMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slider_sMouseReleased
        // TODO add your handling code here:
        if (opened)
            s = Process.hsvThres(lbl_s_val, lbl_s1_val, slider_s, slider_s1, img_hsv, lbl_img_s_thres, 1);
    }//GEN-LAST:event_slider_sMouseReleased

    private void slider_sMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slider_sMouseDragged
        // TODO add your handling code here:
        if (opened)
            s = Process.hsvThres(lbl_s_val, lbl_s1_val, slider_s, slider_s1, img_hsv, lbl_img_s_thres, 1);
    }//GEN-LAST:event_slider_sMouseDragged

    private void slider_vMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slider_vMouseDragged
        // TODO add your handling code here:
        if (opened)
            v = Process.hsvThres(lbl_v_val, lbl_v1_val, slider_v, slider_v1, img_hsv, lbl_img_v_thres, 2);
    }//GEN-LAST:event_slider_vMouseDragged

    private void slider_vMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slider_vMouseReleased
        // TODO add your handling code here:
        if (opened)
            v = Process.hsvThres(lbl_v_val, lbl_v1_val, slider_v, slider_v1, img_hsv, lbl_img_v_thres, 2);
    }//GEN-LAST:event_slider_vMouseReleased

    private void btn_thresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thresActionPerformed
        // TODO add your handling code here:
        if (opened)
            thres();
    }//GEN-LAST:event_btn_thresActionPerformed

    private void thres() {
        mask=Process.getMask(h, s, v);
        Draw.drawToLabelScaled(mask, lbl_img_mask);

        int pic_area = img_awal.width() * img_awal.height();
        double limit_area = (Integer.parseInt(fieldArea.getText()) / 1000.0) * pic_area;
        System.out.println("limit area :" + limit_area + ", pic area : " + pic_area);

        double overlap = (Integer.parseInt(fieldOverlap.getText())) / 100.0;
        System.out.println("overlap :" + overlap);

        data=Process.cropROI(Process.findROI( mask,limit_area, overlap),img_awal);
        Draw.drawToLabelScaled(data.get(data.size() - 1), lbl_img_other);
        x.drawToLabelScaled(data.get(data.size() - 1));
    }

    private void btnSVMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSVMActionPerformed
        // TODO add your handling code here:
        if (opened) {
            labelResult.setText("");
            if (Process.svm(data) == Process.AML) {
                labelResult.setText("AML");
            } else {
                labelResult.setText("ALL");
            }
        }
    }//GEN-LAST:event_btnSVMActionPerformed

    private void slider_h1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slider_h1MouseDragged
        // TODO add your handling code here:
        if (opened)
            h = Process.hsvThres(lbl_h_val, lbl_h1_val, slider_h, slider_h1, img_hsv, lbl_img_h_thres, 0);
    }//GEN-LAST:event_slider_h1MouseDragged

    private void slider_h1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slider_h1MouseReleased
        // TODO add your handling code here:
        if (opened)
            h = Process.hsvThres(lbl_h_val, lbl_h1_val, slider_h, slider_h1, img_hsv, lbl_img_h_thres, 0);
    }//GEN-LAST:event_slider_h1MouseReleased

    private void slider_s1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slider_s1MouseDragged
        // TODO add your handling code here:
        if (opened)
            s = Process.hsvThres(lbl_s_val, lbl_s1_val, slider_s, slider_s1, img_hsv, lbl_img_s_thres, 1);
    }//GEN-LAST:event_slider_s1MouseDragged

    private void slider_s1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slider_s1MouseReleased
        // TODO add your handling code here:
        if (opened)
            s = Process.hsvThres(lbl_s_val, lbl_s1_val, slider_s, slider_s1, img_hsv, lbl_img_s_thres, 1);
    }//GEN-LAST:event_slider_s1MouseReleased

    private void slider_v1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slider_v1MouseDragged
        // TODO add your handling code here:
        if (opened)
            v = Process.hsvThres(lbl_v_val, lbl_v1_val, slider_v, slider_v1, img_hsv, lbl_img_v_thres, 2);
    }//GEN-LAST:event_slider_v1MouseDragged

    private void slider_v1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slider_v1MouseReleased
        // TODO add your handling code here:
        if (opened)
            v = Process.hsvThres(lbl_v_val, lbl_v1_val, slider_v, slider_v1, img_hsv, lbl_img_v_thres, 2);
    }//GEN-LAST:event_slider_v1MouseReleased

    private void fieldOverlapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldOverlapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldOverlapActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
        //jButton2.setBackground(new Color(196,196,196));
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited
        //.setBackground(Color.WHITE);
    }//GEN-LAST:event_jButton2MouseExited

    private void jButton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseEntered
        //jButton3.setBackground(new Color(196,196,196));
    }//GEN-LAST:event_jButton3MouseEntered

    private void jButton3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseExited
        //.setBackground(Color.WHITE);
    }//GEN-LAST:event_jButton3MouseExited

    private void lbl_img_otherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_img_otherMouseClicked
        // TODO add your handling code here:
        if (opened) {
            x.setVisible(true);
            x.drawToLabelScaled(data.get(data.size() - 1));

        }
    }//GEN-LAST:event_lbl_img_otherMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        w.setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSVM;
    private javax.swing.JButton btn_open;
    private javax.swing.JButton btn_thres;
    private javax.swing.JTextField fieldArea;
    private javax.swing.JTextField fieldOverlap;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel labelResult;
    private javax.swing.JLabel lbl_h1_val;
    private javax.swing.JLabel lbl_h_val;
    private javax.swing.JLabel lbl_img_h;
    private javax.swing.JLabel lbl_img_h_thres;
    private javax.swing.JLabel lbl_img_mask;
    private javax.swing.JLabel lbl_img_other;
    private javax.swing.JLabel lbl_img_s;
    private javax.swing.JLabel lbl_img_s_thres;
    private javax.swing.JLabel lbl_img_src;
    private javax.swing.JLabel lbl_img_v;
    private javax.swing.JLabel lbl_img_v_thres;
    private javax.swing.JLabel lbl_s1_val;
    private javax.swing.JLabel lbl_s_val;
    private javax.swing.JLabel lbl_v1_val;
    private javax.swing.JLabel lbl_v_val;
    private javax.swing.JSlider slider_h;
    private javax.swing.JSlider slider_h1;
    private javax.swing.JSlider slider_s;
    private javax.swing.JSlider slider_s1;
    private javax.swing.JSlider slider_v;
    private javax.swing.JSlider slider_v1;
    // End of variables declaration//GEN-END:variables
}
